server:
   port: 8100
      
spring:
  application:
    name: ZuulGateway
    
zuul:
   routes:
    coupon:
      url: http://localhost:8080
    admin:
      url: http://localhost:8081
#      DEALER-APP:
#         serviceId: DEALER-APP
#      FARMER-APP:
#         serviceId: FARMER-APP
#      ADMINMICROSERVICE:
#         serviceId: ADMINMICROSERVICE
##      login-service:
##         url: http://localhost:9004
#      CROPMICROSERVICE:
#         serviceId: CROPMICROSERVICE